version: '2'
services:
  backend:
    container_name: snippets_backend
    build:
      context: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - MYSQL_HOST=mysql

      - MYSQL_USER
      - MYSQL_DATABASE
      - DJANGO_DEBUG
      - DJANGO_SECRET_KEY
      - REDIS_PASSWORD
      - MYSQL_PASSWORD
      - SOCIAL_AUTH_GITHUB_KEY
      - SOCIAL_AUTH_GITHUB_SECRET
    links:
      - mysql
      - redis
    ports:
      - "8000:80"
    command: gunicorn -w 1 -b :80 --reload --log-level debug djangosnippets.wsgi:application

  mysql:
    image: mysql:8.0
    container_name: snippets_mysql
    environment:
      - MYSQL_USER
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - ./databases/mysql:/etc/mysql/conf.d

  redis:
    image: redis:latest
    container_name: snippets_redis
    environment:
      - REDIS_PASSWORD
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
