# Generated by Django 2.2 on 2019-04-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='下書き'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='snippet',
            table='snippets',
        ),
    ]
