# Generated by Django 2.0rc1 on 2017-11-26 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20171127_0329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='posted_by',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='created_date',
        ),
        migrations.AddField(
            model_name='snippet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='投稿日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
